### ISSUE TITLE
too many arguments to function ‘SDL_GetKeyboardState’

### ISSUE THREAD

**Issue by wayneker** [sdl2-vapi/sdl2-vapi#12]
The following code:

```
static uint8[] state;
int[] numkeys
state = Input.Keyboard.get_state (numkeys);
```

produces the following error:

```
/home/wblaszcz/MyVala/opengl/src/sdl-cubes.vala.c:349:11: error: too many arguments to function ‘SDL_GetKeyboardState’
  _tmp4_ = SDL_GetKeyboardState (_tmp2_, _tmp2__length1, &_tmp3_);
           ^
In file included from /home/wblaszcz/MyVala/opengl/src/sdl-cubes.vala.c:11:0:
/usr/include/SDL2/SDL_keyboard.h:77:38: note: declared here
 extern DECLSPEC const Uint8 *SDLCALL SDL_GetKeyboardState(int *numkeys);
                                      ^
```

According to the SDL documentation, numkeys should return the length of the returned array, so I'm not sure why an array is declared. Also a null can be passed in.

To cut a long story short, I finally go this to work by removing the numkeys parameter all together from the vapi file.
e.g. state = Input.Keyboard.get_state ();

Not sure if it was the right thing to do, but it works.

Regards,
Wayne.

**Comment by desiderantes** [comment]
Yes, that was incorrectly binded, thanks for the report
