### ISSUE TITLE
Multiple Syntax Errors

### ISSUE THREAD

**Issue by darkoverlordofdata** [sdl2-vapi/sdl2-vapi#17]
The install script fails:
bash: ./INSTALL: /usr/bin/sh: bad interpreter: No such file or directory
bruce@barsoom:~/Git/sdl2-vapi$ ./INSTALL

I fixed that, and it still fails.
cp: cannot stat ‘./*.{vapi,deps}’: No such file or directory

So I copied them manually. Then I tried the example.
It also fails:
dl2.vapi:1153.27-1153.33: error: syntax error, expected `)'
    [CCode (cname = "Uint32" cprefix = "SDL_MOUSEWHEEL_", has_type_id = false, cheader_filename = "SDL2/SDL_events.h")]
                             ^^^^^^^
sdl2.vapi:2905.4-2905.9: error: syntax error, expected`{'
            public string? name {
            ^^^^^^
Compilation failed: 2 error(s), 0 warning(s)

**Comment by desiderantes** [comment]
Please try again

**Comment by darkoverlordofdata** [comment]
Well, now it compiles, but it get's a run time error ;)
ERROR:/home/bruce/Git/sdl2-vapi/examples/basics.vala.c:169:example_main: assertion failed: (window_renderer == null)
Aborted (core dumped)

You now what, I'm ok with that - I was only trying this program to verify the libraries. I found that I could verify them by running these examples:

https://github.com/Serranya/sdl2-vala-lazy-foo

**Comment by desiderantes** [comment]
That error means that SDL2 was unable to create a window for you. Might want to add a call to get_error() to see what's happening, but since that's beyond this issue, i'm closing it
