### ISSUE TITLE
Add [Version] attribute

### ISSUE THREAD

**Issue by desiderantes** [sdl2-vapi/sdl2-vapi#18]
Since There's now a [Version (since="x.yy.z")] attribute in valac, we need to document the versions of every enum, function and delegate in the vapis. Maybe this can wait until Vala 0.32 is released.

**Comment by zeroandnull** [comment]
I can take this on. I was going to comb through the API anyway to ensure the latest changes to SDL have bindings.

**Comment by desiderantes** [comment]
No longer maintained
