### ISSUE TITLE
Wrong applied @desiderantes commits

### ISSUE THREAD

**Issue by desiderantes** [sdl2-vapi/sdl2-vapi#2]
Only a few structs are meant to be user-generated, and those should have padding to be used. However, received structs, like Events, are not meant to be user generated, and thus, padding is not needed.

**Comment by PedroHLC** [comment]
Wow, you're fast, I'm redoing the merge of ours repos cause somethings gone wrong in my first try, please dis-considerate what you first saw some seconds ago...

**Comment by PedroHLC** [comment]
Is it ok now in the branch "leagueofvala" ??

**Comment by desiderantes** [comment]
No, I did some changes, like renaming GLattr to GL.Attributes, that you have partially undone on that branch. Maybe recreating the commits would work better than just forcing a merge

**Comment by PedroHLC** [comment]
There were differences between my branch and @txasatonga since he accidentaly forced an push in gitourious, I rolledback two GLattr renamings cause the referenced cname that seems to not exist(they've ended with an 's', that at least is not documented). Don't worry, I'll fix it.

**Comment by PedroHLC** [comment]
In 014b604ca9659f179fee26d2077952df53862eef I've used "git diff" to make sure nothing was wrong, in the end, almost all your commits replaced mines. I've chosen to put the static "get_name" from "Joystick" as "get_name_from_index", adding vapi binding doesn't change the final project result and we can cover more uses for the same function.

**Comment by PedroHLC** [comment]
Any other change suggested?

**Comment by desiderantes** [comment]
SDL_JoystickNameForIndex was already binded under the name_forindex name. I'll cahnge it to get_name_for_index in my repo because that wasn't a good name. maybe you should retry the merge in a few minutes.

**Comment by PedroHLC** [comment]
Anything else?
