### ISSUE TITLE
KeyboardState leads to segmentation fault

### ISSUE THREAD

**Issue by gwutz** [sdl2-vapi/sdl2-vapi#20]
according to 
https://wiki.libsdl.org/SDL_GetKeyboardState
the caller shouldnt free the keyboardstate - its a pointer to a "till the end of application" array.

So using Input.Keyboard.get_state() leads to a free-call which leads to a segmentation fault. I solved it at the moment with an **unowned** uint8[] get_state() change in sdl2.vapi.

**Comment by desiderantes** [comment]
Looks like the method was bound in a hurry, sorry. I think that actually that should be a bool array, given the expected value range.

**Comment by desiderantes** [comment]
What i think would solve this is having a get_raw_state(out uint numkeys = null) function, returning the pointer, and bool[] get_state() which calls the former, casts to bool[] and correctly sets the length, while preserving the pointer so we can update the info vía SDL_PumpEvents()

**Comment by desiderantes** [comment]
Ok, i have some code with the fixes i proposed, gotta test it some more and the push it. Is anybody against my solution?
