### ISSUE TITLE
SDLTTF Font information lead to segfault

### ISSUE THREAD

**Issue by gwutz** [sdl2-vapi/sdl2-vapi#21]
Hey guys,

another problem i ran into: i loaded a Font with SDLTTF and queried the font style name. This string shouldnt be freed by vala because its managed by SDLTTF (as far as i think - i didn't found information about who owns that memory at all - i just debugged my programm and recognized that a free-function of that string led to a segfault)

Maybe we have to declare them unowned. I tried it just now with 

```
public unowned string get_style_name()
```

and it worked. So problem the other functions are need the same love.

Greets
Günther

**Comment by desiderantes** [comment]
Thanks for the catch! Again, inherited code. Most methods there actually need some renaming, UTF-8 is the righteous default, and both UTF-16 and Latin-1 are deviant encodings that deserve special naming  so i'll rename a couple of functions :stuck_out_tongue_winking_eye:

**Comment by gwutz** [comment]
Hey if you need some help i would be glad to help out. Seems like you are the only maintainer and i think sdl2 should be part of vala!

**Comment by desiderantes** [comment]
Thanks! Actually, sdl2-vapi is included in vala-extra-vapis, so it's as included as it can be without any stability guarantee (as the vapi is not stable yet). Also, I'm actualy revamping SDLTTF right now! It has some missing methods and the types are mostly wrong, so expect changes today.

**Comment by desiderantes** [comment]
Please test the changes i just pushed in a653f4d

**Comment by desiderantes** [comment]
Closing, keep in mind that SDLTTF returns nullable strings, so remember to check for that.
