### ISSUE TITLE
Cannot access functions under SDL.Video.Display

### ISSUE THREAD

**Issue by zeroandnull** [sdl2-vapi/sdl2-vapi#24]
I have **absolutely no idea** how to invoke any of the functions bound under SDL.Video.Display:
- SDL_GetDisplayName
- SDL_GetDisplayBounds
- SDL_GetNumDisplayModes
- SDL_GetDisplayMode
- SDL_GetDisplayDPI
- SDL_GetDesktopDisplayMode
- SDL_GetCurrentDisplayMode
- SDL_GetClosestDisplayMode

Would have contacted @desiderantes directly, but I could not find any personal contact info.

The binding declares Display as a struct, yet the SDL library does not. Is the binding correct or does it need to be modified? If correct, please let me know the proper way to invoke these functions. If not correct, I can volunteer to provide a fix.

**Comment by desiderantes** [comment]
`SDL.Video.Display` is a [SimpleType](https://wiki.gnome.org/Projects/Vala/LegacyBindings#Simple_Types) struct, inheriting form int, that means it's just a pumped up number. Usually, you'd check `SDL.Video.num_displays()`and cast an integer to the appropiated type. For example: 

```
int display_count = SDL.Video.num_displays();
assert ( display_count > 0);
for (int i = 0 ; i< display_count; i++ ){
    var current = (SDL.Video.Display) i;
    //get crazy here!
}
```

It's not an error, just missing documentation (#3)

**Comment by zeroandnull** [comment]
Good, so the intended use is as I though (which means I'm not crazy)! However you still get a compilation error from the C compiler when you try your example complaining about a nonexistent "SDL_VideoDisplay" type. The binding is not preventing valac from thinking that there is an actual underlying struct type.

I'll investigate this further when I get home later today.

**Comment by desiderantes** [comment]
The cast might not be needed, but i'll check later when i'm home
