### ISSUE TITLE
Rename files to match pkg-config filenames

### ISSUE THREAD

**Issue by astavale** [sdl2-vapi/sdl2-vapi#42]
This makes it easier to build Vala programs with SDL2 because the linker arguments don't have to be added manually. They can be found by `pkg-config` instead. For example, some of the corrected names would be:

SDL2_image.vapi
SDL2_mixer.vapi
SDL2_ttf.vapi

See https://github.com/darkoverlordofdata/shmupwarz-vala/tree/master/src/vapis for a working example.

**Comment by desiderantes** [comment]
Hey, thanks for the report! I agree with the rename, can you send a PR for this?
