### ISSUE TITLE
uppercase, - vs _ inconsistencies

### ISSUE THREAD

**Issue by dufresnep** [sdl2-vapi/sdl2-vapi#45]
how_install_sdl2_Graphics suggest to use:
valac -o appname --pkg sdl2 --pkg sdl2-gfx --pkg sdl2-ttf --pkg sdl2-image --pkg sdl2-mixer -X -lSDL2_image -X -lSDL2_ttf -X -lSDL2_mixer -X -lSDL2_gfx appname.vala

and I believe this should be it!
But it is not, it would more be:
valac -o appname --pkg sdl2 --pkg SDL2_gfx --pkg SDL2_ttf --pkg SDL2_image --pkg SDL2_mixer -X -lSDL2_image -X -lSDL2_ttf -X -lSDL2_mixer -X -lSDL2_gfx appname.vala

So I suggest the files be renamed from SDL2_* to sdl2-*
I wonder if in the past both would be accepted on Linux, but here with Fedora and
valac 0.42, both changes seems necessary.

**Comment by desiderantes** [comment]
Yes, we changed the names but forgot to update the instructions
