### ISSUE TITLE
basics.vala: `SDLImage' does not exist in the context of `SDLSample.main'

### ISSUE THREAD

**Issue by dufresnep** [sdl2-vapi/sdl2-vapi#47]
While compiling basics.vala with (valac 0.42.2)
valac --pkg sdl2 --pkg SDL2_gfx -o basics -X -lSDL2_image -X -lSDL2_ttf -X -lSDL2_mixer -X -lSDL2_gfx -v basics.vala

I got:
basics.vala:82.44-82.51: error: The name `SDLImage' does not exist in the context of `SDLSample.main'
        SDL.init (SDL.InitFlag.EVERYTHING| SDLImage.InitFlags.ALL);

**Comment by desiderantes** [comment]
You forgot the `--pkg` argument for SDL2-Image

**Comment by desiderantes** [comment]
Check the fixes for your other issues, you should just pass the --pkg parameter and not deal with passing parameters to the C compiler
