### ISSUE TITLE
[Compile Error] Enum usage as array size 

### ISSUE THREAD

**Issue by gavr123456789** [sdl2-vapi/sdl2-vapi#53]
Enum cannot be used in place of the array index.  
[Here](https://github.com/sdl2-vapi/sdl2-vapi/blob/master/vapis/sdl2.vapi#L3370) it is.  
![image](https://user-images.githubusercontent.com/30507409/78068815-c1687a00-73a1-11ea-95c2-480db51f23c1.png)

**Comment by desiderantes** [comment]
Try with Vala nightly

**Comment by gavr123456789** [comment]
Works with Vala 0.48.2.15-aa564  
(5 min for build it, why it still using autotools when meson branch works perfectly)  
I correctly understand that absolutely the same effect will be if I replace `SDL.Video.MessageBox.ColorType.MAX` by `5`?

**Comment by desiderantes** [comment]
The value is currently 5, yes, but it could change in the future. If you need it working on prior Vala versions, just revert https://github.com/sdl2-vapi/sdl2-vapi/commit/9ae5a8192c71eabef30dd81b4ae7d88408a1ebb5

**Comment by gavr123456789** [comment]
Okay thanks for the work. (and quick response ^^)
