### ISSUE TITLE
Proper namespace separation

### ISSUE THREAD

**Issue by desiderantes** [sdl2-vapi/sdl2-vapi#8]
To keep a clean separation, namespaces should be used to separate functionality by category. Something like the separation on [SDL2 wiki](https://wiki.libsdl.org/APIByCategory), but some categories should be fused. I propose the following separation:
- SDL
- Video
- Audio
- Input
- Haptic
- Threading (maybe a better name for this one)

It would also make easy to document the binding and make ithe docs more similar to the SDL2 wiki.

**Comment by PedroHLC** [comment]
As they all are core features, shouldn't it be SDL.Video, SDL.Audio, SDL.Input...? Though this separation would be useless cause most classes depends on each other, they never repeate any name, separating would only distanciate them from the original C API (which won't be a problem if the doc get complete).

**Comment by Serranya** [comment]
Napespace spearation has an additional benefit. You can make method and type names shorter.
As an example:

```
struct HintPriority {
    //...
}

add_hint_callback(HintCallback c)
```

Can be made shorter if they are in their own namespace:

```
namespace Hint {
    struct Priority {
        //....
    }

    add_callback(Callback c)
}
```

**Comment by desiderantes** [comment]
@PedroHLC , well, in this case, all the other namespaces would be nested inside the SDL namespace. Look the audio namespace i already added, for example.

@Serranya The problem is, that could also add more words to other subsystems, like SDL.Input.Cursor or SDL.Video.Surface (solvable via _using_ statements, like _using SDL.Video_) Also, in you example, it would be better to do add_callback(Hint.Callback callback); for there is also Audio.Callback

**Comment by PedroHLC** [comment]
SDL.Graphics.{Rect, Point} can be generally used as measuring tools to bi-dimensional vectors/matrices not only bitmaps, shouldn't they be outside Graphics? They can be very useful as geometry functions...

**Comment by desiderantes** [comment]
Well, they are in the "Video" Category of SDL, so i added them in that category too. IMHO, Rect and Point do not have a good use case as measurement tools, they are mostly used to describe a geometry, and geometry is a Graphic topic, hence the Graphics namespace. Nobody will try to do audio processing with those structs, for example. Since the usage domain is still restricted to Graphics related tasks, i think they should remain in that category. What do you think, @PedroHLC @txasatonga @Serranya ?

**Comment by Serranya** [comment]
While i agree that the topic "Geometry" (to which Rect/Point belongs) is broader than just "Graphics" I think we schould leave Rect/Point in SDL.Graphics.

**Comment by desiderantes** [comment]
Revisiting this vapi, i think SDL.Graphics should be renamed to SDL.Video. A similar flattening occurred on SDL.Audio, so the methods on SDL.Graphics.Video can become static methods on a Video namespace. What do you think?
